 require "rails_helper"

 # This spec was generated by rspec-rails when you ran the scaffold generator.
 # It demonstrates how one might use RSpec to test the controller code that
 # was generated by Rails when you ran the scaffold generator.
 #
 # It assumes that the implementation code is generated by the rails scaffold
 # generator. If you are using any extension libraries to generate different
 # controller code, this generated spec may or may not pass.
 #
 # It only uses APIs available in rails and/or rspec-rails. There are a number
 # of tools you can use to make these specs even more expressive, but we're
 # sticking to rails and rspec-rails APIs to keep things simple and stable.

 RSpec.describe "/account_transactions", type: :request do
   # AccountTransaction. As you add validations to AccountTransaction, be sure to
   # adjust the attributes here as well.
   let(:valid_attributes) {
     attributes_for(:account_transaction)
   }

   describe "GET /index" do
     it "renders a successful response" do
       get account_transactions_url
       expect(response).to be_successful
     end
   end

   describe "GET /show" do
     it "renders a successful response" do
       account_transaction = create(:account_transaction)
       get account_transaction_url(account_transaction)
       expect(response).to be_successful
     end
   end
 end
