 require "rails_helper"

 # This spec was generated by rspec-rails when you ran the scaffold generator.
 # It demonstrates how one might use RSpec to test the controller code that
 # was generated by Rails when you ran the scaffold generator.
 #
 # It assumes that the implementation code is generated by the rails scaffold
 # generator. If you are using any extension libraries to generate different
 # controller code, this generated spec may or may not pass.
 #
 # It only uses APIs available in rails and/or rspec-rails. There are a number
 # of tools you can use to make these specs even more expressive, but we're
 # sticking to rails and rspec-rails APIs to keep things simple and stable.

 RSpec.describe "/cnab_imports", type: :request do
   # CnabImport. As you add validations to CnabImport, be sure to
   # adjust the attributes here as well.
   describe "GET /new" do
     it "renders a successful response" do
       get new_cnab_import_url
       expect(response).to be_successful
     end
   end

   describe "POST /create" do
     context "with valid parameters" do
       it "creates a new CnabImport" do
         expect {
           post cnab_imports_url, params: { cnab_import: attributes_for(:cnab_import) }
         }.to change(CnabImport, :count).by(1)
       end

       it "redirects to the transactions page" do
         post cnab_imports_url, params: { cnab_import: attributes_for(:cnab_import) }
         expect(response).to redirect_to(account_transactions_url)
       end
     end
   end
 end
